### ISSUE TITLE
[BUG] yarn 2 pnp issues

### ISSUE THREAD

**Issue by regevbr** [mapbox/node-sqlite3#1312]
The library requires the node-gyp package when there is no existing pre built binaries but it is not declared as a dependency. 

Because yarn 2 uses PlugNPlay, it is not allowed to use non declared dependencies, causing my CI tools to fail

Temp fix is to add to .yarnrc.yml
```yaml
packageExtensions:
  sqlite3@*:
    dependencies:
      node-gyp: "*"
```
